In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

## Load the training data into feature matrix, class labels, and event ids:

In [2]:
!ls

__pycache__      proj1_helpers.py project1.ipynb


In [4]:
from proj1_helpers import *
DATA_TRAIN_PATH = '/Users/jonathandoenz/Dropbox/EPFL_2018-2019/Semester_1/ML/ML_course/projects/project1/data/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

## Exploration using Pandas

In [29]:
import pandas as pd

In [30]:
df = pd.read_csv(DATA_TRAIN_PATH)

In [31]:
df.head()

Id Prediction  DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  \
0  100000          s       138.470                       51.655        97.827   
1  100001          b       160.937                       68.768       103.235   
2  100002          b      -999.000                      162.172       125.953   
3  100003          b       143.905                       81.417        80.943   
4  100004          b       175.864                       16.915       134.805   

   DER_pt_h  DER_deltaeta_jet_jet  DER_mass_jet_jet  DER_prodeta_jet_jet  \
0    27.980                  0.91           124.711                2.666   
1    48.146               -999.00          -999.000             -999.000   
2    35.635               -999.00          -999.000             -999.000   
3     0.414               -999.00          -999.000             -999.000   
4    16.405               -999.00          -999.000             -999.000   

   DER_deltar_tau_lep  ...  PRI_met_phi  PRI_met_sumet  PRI_jet_num  \
0               3.064  ...       -0.277        258.733            2   
1               3.473  ...       -1.916        164.546            1   
2               3.148  ...       -2.186        260.414            1   
3               3.310  ...        0.060         86.062            0   
4               3.891  ...       -0.871         53.131            0   

   PRI_jet_leading_pt  PRI_jet_leading_eta  PRI_jet_leading_phi  \
0              67.435                2.150                0.444   
1              46.226                0.725                1.158   
2              44.251                2.053               -2.028   
3            -999.000             -999.000             -999.000   
4            -999.000             -999.000             -999.000   

   PRI_jet_subleading_pt  PRI_jet_subleading_eta  PRI_jet_subleading_phi  \
0                 46.062                    1.24                  -2.475   
1               -999.000                 -999.00                -999.000   
2               -999.000                 -999.00                -999.000   
3               -999.000                 -999.00                -999.000   
4               -999.000                 -999.00                -999.000   

   PRI_jet_all_pt  
0         113.497  
1          46.226  
2          44.251  
3           0.000  
4           0.000  

[5 rows x 32 columns]

In [32]:
df_withNa = df.copy()
df_withNa[df_withNa == -999] = np.nan

In [33]:
df_withNa.head()

Id Prediction  DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  \
0  100000          s       138.470                       51.655        97.827   
1  100001          b       160.937                       68.768       103.235   
2  100002          b           NaN                      162.172       125.953   
3  100003          b       143.905                       81.417        80.943   
4  100004          b       175.864                       16.915       134.805   

   DER_pt_h  DER_deltaeta_jet_jet  DER_mass_jet_jet  DER_prodeta_jet_jet  \
0    27.980                  0.91           124.711                2.666   
1    48.146                   NaN               NaN                  NaN   
2    35.635                   NaN               NaN                  NaN   
3     0.414                   NaN               NaN                  NaN   
4    16.405                   NaN               NaN                  NaN   

   DER_deltar_tau_lep  ...  PRI_met_phi  PRI_met_sumet  PRI_jet_num  \
0               3.064  ...       -0.277        258.733            2   
1               3.473  ...       -1.916        164.546            1   
2               3.148  ...       -2.186        260.414            1   
3               3.310  ...        0.060         86.062            0   
4               3.891  ...       -0.871         53.131            0   

   PRI_jet_leading_pt  PRI_jet_leading_eta  PRI_jet_leading_phi  \
0              67.435                2.150                0.444   
1              46.226                0.725                1.158   
2              44.251                2.053               -2.028   
3                 NaN                  NaN                  NaN   
4                 NaN                  NaN                  NaN   

   PRI_jet_subleading_pt  PRI_jet_subleading_eta  PRI_jet_subleading_phi  \
0                 46.062                    1.24                  -2.475   
1                    NaN                     NaN                     NaN   
2                    NaN                     NaN                     NaN   
3                    NaN                     NaN                     NaN   
4                    NaN                     NaN                     NaN   

   PRI_jet_all_pt  
0         113.497  
1          46.226  
2          44.251  
3           0.000  
4           0.000  

[5 rows x 32 columns]

### NaN values exploration

In [34]:
Na_series = df_withNa.isna().sum()
Na_series

Id                                  0
Prediction                          0
DER_mass_MMC                    38114
DER_mass_transverse_met_lep         0
DER_mass_vis                        0
DER_pt_h                            0
DER_deltaeta_jet_jet           177457
DER_mass_jet_jet               177457
DER_prodeta_jet_jet            177457
DER_deltar_tau_lep                  0
DER_pt_tot                          0
DER_sum_pt                          0
DER_pt_ratio_lep_tau                0
DER_met_phi_centrality              0
DER_lep_eta_centrality         177457
PRI_tau_pt                          0
PRI_tau_eta                         0
PRI_tau_phi                         0
PRI_lep_pt                          0
PRI_lep_eta                         0
PRI_lep_phi                         0
PRI_met                             0
PRI_met_phi                         0
PRI_met_sumet                       0
PRI_jet_num                         0
PRI_jet_leading_pt              99913
PRI_jet_lead

In [35]:
Na_dict = {value: [index_name for index_name in Na_series.index if Na_series[index_name] == value] for value in Na_series.values}
Na_dict

{0: ['Id',
  'Prediction',
  'DER_mass_transverse_met_lep',
  'DER_mass_vis',
  'DER_pt_h',
  'DER_deltar_tau_lep',
  'DER_pt_tot',
  'DER_sum_pt',
  'DER_pt_ratio_lep_tau',
  'DER_met_phi_centrality',
  'PRI_tau_pt',
  'PRI_tau_eta',
  'PRI_tau_phi',
  'PRI_lep_pt',
  'PRI_lep_eta',
  'PRI_lep_phi',
  'PRI_met',
  'PRI_met_phi',
  'PRI_met_sumet',
  'PRI_jet_num',
  'PRI_jet_all_pt'],
 38114: ['DER_mass_MMC'],
 177457: ['DER_deltaeta_jet_jet',
  'DER_mass_jet_jet',
  'DER_prodeta_jet_jet',
  'DER_lep_eta_centrality',
  'PRI_jet_subleading_pt',
  'PRI_jet_subleading_eta',
  'PRI_jet_subleading_phi'],
 99913: ['PRI_jet_leading_pt', 'PRI_jet_leading_eta', 'PRI_jet_leading_phi']}

In [36]:
Na_dict.get(177457)

['DER_deltaeta_jet_jet',
 'DER_mass_jet_jet',
 'DER_prodeta_jet_jet',
 'DER_lep_eta_centrality',
 'PRI_jet_subleading_pt',
 'PRI_jet_subleading_eta',
 'PRI_jet_subleading_phi']

#### Question: Are the NaNs of the columns with the same total number of NaNs for the same records?

In [37]:
N_all_177457 = df_withNa.dropna(subset=Na_dict.get(177457), how='all').shape[0]

In [38]:
N - N_all_177457 == 177457

False

Removing the records having a NaN in all the columns having 177457 NaNs in total removes exactly 177457 records. Therefore the 177457 NaNs are for the same records.

In [39]:
N_all_99913 = df_withNa.dropna(subset=Na_dict.get(99913), how='all').shape[0]

In [40]:
N - N_all_99913 == 99913

False

Removing the records having a NaN in all the columns having 99913 NaNs in total removes exactly 99913 records. Therefore the 99913 NaNs are for the same records.

#### Is "DER_MMC" missing in combination with other missing values?

In [41]:
N_mass_and_177457 = N - df_withNa.dropna(subset=["DER_mass_MMC", "DER_deltaeta_jet_jet"], how='all').shape[0]
N_mass_and_177457

-211315

In [42]:
df_2 = df_withNa[df_withNa.DER_mass_MMC.isna() & df_withNa.PRI_jet_subleading_pt.notna()].drop("DER_mass_MMC", axis=1)

In [43]:
df_2.isna().sum()

Id                             0
Prediction                     0
DER_mass_transverse_met_lep    0
DER_mass_vis                   0
DER_pt_h                       0
DER_deltaeta_jet_jet           0
DER_mass_jet_jet               0
DER_prodeta_jet_jet            0
DER_deltar_tau_lep             0
DER_pt_tot                     0
DER_sum_pt                     0
DER_pt_ratio_lep_tau           0
DER_met_phi_centrality         0
DER_lep_eta_centrality         0
PRI_tau_pt                     0
PRI_tau_eta                    0
PRI_tau_phi                    0
PRI_lep_pt                     0
PRI_lep_eta                    0
PRI_lep_phi                    0
PRI_met                        0
PRI_met_phi                    0
PRI_met_sumet                  0
PRI_jet_num                    0
PRI_jet_leading_pt             0
PRI_jet_leading_eta            0
PRI_jet_leading_phi            0
PRI_jet_subleading_pt          0
PRI_jet_subleading_eta         0
PRI_jet_subleading_phi         0
PRI_jet_al

In [44]:
df_withNa[df_withNa.DER_mass_MMC.isna() & df_withNa.PRI_jet_subleading_pt.notna()][df_withNa.columns != "DER_mass_MMC"].isna()#.head(1)#.shape[0]

ValueError: Item wrong length 32 instead of 4429.

#### How do NaNs overlap between the 177457 and the 99913 groups?

In [45]:
Na_series.get(99913)

In [46]:
N_neither_177457_99913 = N - df_withNa.dropna(subset=[Na_dict.get(177457)[0], Na_dict.get(99913)[0]], how='all').shape[0]
# N - N_neither_177457_99913

In [47]:
N_any_of_177457_99913 = N - df_withNa.dropna(subset=[Na_dict.get(177457)[0], Na_dict.get(99913)[0]], how='any').shape[0]
# N - N_neither_177457_99913

In [48]:
N_any_of_177457_99913

-67543

In [49]:
N_neither_177457_99913

-145087

Therefore the 99913 NaNs are only present in the records missing the 177457 columns' values as well!

In [50]:

df_withNa[df_withNa.DER_mass_MMC.isna()].

SyntaxError: invalid syntax (<ipython-input-50-87a95a09006f>, line 2)

In [51]:
df_withNa.describe()

Id   DER_mass_MMC  DER_mass_transverse_met_lep  \
count  250000.000000  211886.000000                250000.000000   
mean   224999.500000     121.858528                    49.239819   
std     72168.927986      57.298157                    35.344886   
min    100000.000000       9.044000                     0.000000   
25%    162499.750000      91.885250                    19.241000   
50%    224999.500000     112.406000                    46.524000   
75%    287499.250000     135.482000                    73.598000   
max    349999.000000    1192.026000                   690.075000   

        DER_mass_vis       DER_pt_h  DER_deltaeta_jet_jet  DER_mass_jet_jet  \
count  250000.000000  250000.000000          72543.000000      72543.000000   
mean       81.181982      57.895962              2.403735        371.783360   
std        40.828691      63.655682              1.742226        397.699325   
min         6.329000       0.000000              0.000000         13.602000   
25%        59.388750      14.068750              0.882500        111.977000   
50%        73.752000      38.467500              2.107000        225.885000   
75%        92.259000      79.169000              3.690000        478.226000   
max      1349.351000    2834.999000              8.503000       4974.979000   

       DER_prodeta_jet_jet  DER_deltar_tau_lep     DER_pt_tot  ...  \
count         72543.000000       250000.000000  250000.000000  ...   
mean             -0.821688            2.373100      18.917332  ...   
std               3.584362            0.782911      22.273494  ...   
min             -18.066000            0.208000       0.000000  ...   
25%              -2.629000            1.810000       2.841000  ...   
50%              -0.244000            2.491500      12.315500  ...   
75%               0.958000            2.961000      27.591000  ...   
max              16.690000            5.684000    2834.999000  ...   

         PRI_met_phi  PRI_met_sumet    PRI_jet_num  PRI_jet_leading_pt  \
count  250000.000000  250000.000000  250000.000000       150087.000000   
mean       -0.010119     209.797178       0.979176           84.822105   
std         1.812223     126.499506       0.977426           60.662276   
min        -3.142000      13.678000       0.000000           30.000000   
25%        -1.575000     123.017500       0.000000           44.422500   
50%        -0.024000     179.739000       1.000000           65.561000   
75%         1.561000     263.379250       2.000000          103.342000   
max         3.142000    2003.976000       3.000000         1120.573000   

       PRI_jet_leading_eta  PRI_jet_leading_phi  PRI_jet_subleading_pt  \
count        150087.000000        150087.000000           72543.000000   
mean             -0.003275            -0.012393              57.679474   
std               1.784546             1.813385              31.985782   
min              -4.499000            -3.142000              30.000000   
25%              -1.342000            -1.584000              37.312000   
50%               0.000000            -0.033000              47.902000   
75%               1.336000             1.562000              66.637000   
max               4.499000             3.141000             721.456000   

       PRI_jet_subleading_eta  PRI_jet_subleading_phi  PRI_jet_all_pt  
count            72543.000000            72543.000000   250000.000000  
mean                -0.011845               -0.001582       73.064591  
std                  2.031743                1.816950       98.015662  
min                 -4.500000               -3.142000        0.000000  
25%                 -1.612000               -1.576500        0.000000  
50%                 -0.010000               -0.002000       40.512500  
75%                  1.589500                1.576000      109.933750  
max                  4.500000                3.142000     1633.433000  

[8 rows x 31 columns]

In [52]:
N = df_withNa.shape[0]
N_not_NAN = df_withNa.dropna(how='any').shape[0]

In [53]:
fraction_of_NAN = (N - N_not_NAN)/N
fraction_of_NAN

0.727544

In [54]:
df_withNa.shape, df_withNa.dropna(how='any').shape

((250000, 32), (68114, 32))

### Look at signal/background label distribution for the NaN entries

In [55]:
N = df_withNa.shape[0]
N_s = (df_withNa.Prediction == 's').sum()
N_b = (df_withNa.Prediction == 'b').sum()
s_b_ratio = N_s / N
N_s, N_b, s_b_ratio

(85667, 164333, 0.342668)

34% of the records of the training set are labelled as signal

In [56]:
df_withoutNa = df_withNa.dropna(how='any')

In [57]:
N_notNa = df_withoutNa.shape[0]
N_notNa_s = (df_withoutNa.Prediction == 's').sum()
N_notNa_b = (df_withoutNa.Prediction == 'b').sum()
s_b_notNa_ratio = N_notNa_s / N_notNa
N_notNa, N_notNa_s, N_notNa_b, s_b_notNa_ratio
# N_notNa_s, N_notNa_b

(68114, 31894, 36220, 0.4682444137769034)

47% of the records containing no NA are signal. As it is 13% more than before removing NANs, it suggests that the records containing any NANs are majoritarily noise events.

In [58]:
(df_withNa.dropna(how='all').Prediction == 's').sum()

85667

In [59]:
(df_withNa.dropna(how='all').Prediction == 's').sum()

85667

#### What is the signal ratio for the special case of DER_mass_MMC being NaN?

In [60]:
df_MMCisNa = df_withNa[df_withNa.DER_mass_MMC.isna()]

In [61]:
(df_MMCisNa.Prediction == 's').sum() / df_MMCisNa.shape[0]

0.07438211680747232

Only 7% of the records missing the DER_mass_MMC are labelled as signal.

#### What is the signal ratio for the special case of the 177457 columns being NaN?

In [62]:
df_177457_isNa = df_withNa[ df_withNa.PRI_jet_subleading_pt.isna() ]

In [63]:
(df_177457_isNa.Prediction == 's').sum() / df_177457_isNa.shape[0]

0.299802205604738

In [64]:
df_177457_isNa.shape[0] / N

0.709828

30% of the records missing the 177457s' columns are labelled as signal. It is about the same as the percentage of the dataset. As they make up about 70% of the whole dataset, it is crucial to keep them!

##### Proposition to deal with outliers:

Replace the values of their columns with the mean? 

Problem: This will bias the rest of the data in these columns (which only make up 30% so are minoritary)!

**Best so far:**
Replace the values of their columns with 0?

Advantage: 
It does not contribute to anything when multiplied with the model vector $\vec{w}$.

In [146]:
from implementations import *

In [147]:
y = logistic_function(0)

In [148]:
logistic_function(np.arange(2))

array([0.5       , 0.73105858])

In [136]:
y

0.5

### How are the NaNs distributed in the test dataset?

Training and testing sets have very similar distribution of NaNs.

In [71]:
df_test = pd.read_csv(DATA_TEST_PATH)
df_test.head()

Id Prediction  DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  \
0  350000          ?      -999.000                       79.589        23.916   
1  350001          ?       106.398                       67.490        87.949   
2  350002          ?       117.794                       56.226        96.358   
3  350003          ?       135.861                       30.604        97.288   
4  350004          ?        74.159                       82.772        58.731   

   DER_pt_h  DER_deltaeta_jet_jet  DER_mass_jet_jet  DER_prodeta_jet_jet  \
0     3.036              -999.000          -999.000             -999.000   
1    49.994              -999.000          -999.000             -999.000   
2     4.137              -999.000          -999.000             -999.000   
3     9.104              -999.000          -999.000             -999.000   
4    89.646                 1.347           536.663               -0.339   

   DER_deltar_tau_lep  ...  PRI_met_phi  PRI_met_sumet  PRI_jet_num  \
0               0.903  ...        2.022         98.556            0   
1               2.048  ...       -1.138        176.251            1   
2               2.755  ...       -1.868        111.505            0   
3               2.811  ...        1.172        164.707            0   
4               1.028  ...       -0.231        869.614            3   

   PRI_jet_leading_pt  PRI_jet_leading_eta  PRI_jet_leading_phi  \
0            -999.000             -999.000             -999.000   
1              47.575               -0.553               -0.849   
2            -999.000             -999.000             -999.000   
3            -999.000             -999.000             -999.000   
4             254.085               -1.013               -0.334   

   PRI_jet_subleading_pt  PRI_jet_subleading_eta  PRI_jet_subleading_phi  \
0               -999.000                -999.000                -999.000   
1               -999.000                -999.000                -999.000   
2               -999.000                -999.000                -999.000   
3               -999.000                -999.000                -999.000   
4                185.857                   0.335                   2.587   

   PRI_jet_all_pt  
0           0.000  
1          47.575  
2           0.000  
3           0.000  
4         599.213  

[5 rows x 32 columns]

In [72]:
df_test_withNa = df_test.copy()

In [73]:
df_test_withNa[df_test == -999.0] = np.nan

In [74]:
N_test = df_test_withNa.shape[0]

In [75]:
N = df_withNa.shape[0]

In [76]:
df_withNa.isna().sum() / N

Id                             0.000000
Prediction                     0.000000
DER_mass_MMC                   0.152456
DER_mass_transverse_met_lep    0.000000
DER_mass_vis                   0.000000
DER_pt_h                       0.000000
DER_deltaeta_jet_jet           0.709828
DER_mass_jet_jet               0.709828
DER_prodeta_jet_jet            0.709828
DER_deltar_tau_lep             0.000000
DER_pt_tot                     0.000000
DER_sum_pt                     0.000000
DER_pt_ratio_lep_tau           0.000000
DER_met_phi_centrality         0.000000
DER_lep_eta_centrality         0.709828
PRI_tau_pt                     0.000000
PRI_tau_eta                    0.000000
PRI_tau_phi                    0.000000
PRI_lep_pt                     0.000000
PRI_lep_eta                    0.000000
PRI_lep_phi                    0.000000
PRI_met                        0.000000
PRI_met_phi                    0.000000
PRI_met_sumet                  0.000000
PRI_jet_num                    0.000000


In [77]:
df_test_withNa.isna().sum() / N_test

Id                             0.000000
Prediction                     0.000000
DER_mass_MMC                   0.152204
DER_mass_transverse_met_lep    0.000000
DER_mass_vis                   0.000000
DER_pt_h                       0.000000
DER_deltaeta_jet_jet           0.708851
DER_mass_jet_jet               0.708851
DER_prodeta_jet_jet            0.708851
DER_deltar_tau_lep             0.000000
DER_pt_tot                     0.000000
DER_sum_pt                     0.000000
DER_pt_ratio_lep_tau           0.000000
DER_met_phi_centrality         0.000000
DER_lep_eta_centrality         0.708851
PRI_tau_pt                     0.000000
PRI_tau_eta                    0.000000
PRI_tau_phi                    0.000000
PRI_lep_pt                     0.000000
PRI_lep_eta                    0.000000
PRI_lep_phi                    0.000000
PRI_met                        0.000000
PRI_met_phi                    0.000000
PRI_met_sumet                  0.000000
PRI_jet_num                    0.000000


As we can see, the NaNs in the test's set are distributed very similarly to the ones in the training set.

## Explore data with numpy

In [11]:
from proj1_helpers import *
from implementations import *
DATA_TRAIN_PATH = '/Users/jonathandoenz/Dropbox/EPFL_2018-2019/Semester_1/ML/ML_course/projects/project1/data/train.csv' # TODO: download train data and supply path here 

In [12]:
y, tX, ids = load_csv_data(DATA_TRAIN_PATH, sub_sample=True)

In [13]:
tX.shape

(5000, 30)

In [14]:
tX[0, :]

array([ 1.38470e+02,  5.16550e+01,  9.78270e+01,  2.79800e+01,
        9.10000e-01,  1.24711e+02,  2.66600e+00,  3.06400e+00,
        4.19280e+01,  1.97760e+02,  1.58200e+00,  1.39600e+00,
        2.00000e-01,  3.26380e+01,  1.01700e+00,  3.81000e-01,
        5.16260e+01,  2.27300e+00, -2.41400e+00,  1.68240e+01,
       -2.77000e-01,  2.58733e+02,  2.00000e+00,  6.74350e+01,
        2.15000e+00,  4.44000e-01,  4.60620e+01,  1.24000e+00,
       -2.47500e+00,  1.13497e+02])

Change -999 entries to 0

In [15]:
X = np.copy(tX)

In [16]:
X[X == -999] = 0

Standardize and augment X with ones in its first column

In [17]:
X = standardize_matrix(X)
X = augment_matrix(X)

Initialize parameters for the optimization

In [18]:
N = X.shape[0]
D = X.shape[1]

initial_w = np.zeros(D)
max_iters = 50
gamma = 0.5
method = "SGD"

Make sure my methods function well

In [20]:
batch_size=1

In [21]:
least_squares_SGD(y, X, initial_w, batch_size, max_iters, gamma)

(2.912845982545599e+28,
 array([ 9.43519876e+13, -2.15949636e+14,  3.28917708e+13, -1.10081503e+14,
        -1.07791288e+14, -4.61829076e+13, -3.75840364e+13,  1.09415343e+13,
        -1.07934418e+14, -1.96495672e+13, -1.08354357e+14, -1.50640820e+14,
        -1.15600028e+14, -4.28743885e+13,  6.24094663e+13,  2.91214081e+14,
        -9.16305614e+13, -9.74574334e+13,  8.99468214e+13, -5.51580588e+13,
        -2.04908328e+13,  3.17866913e+13, -3.04922615e+13, -1.86411810e+14,
        -1.54439916e+14, -1.58266323e+13,  1.64816665e+14, -5.01764821e+13,
         3.99391234e+11,  3.51148862e+12, -1.18772995e+14]))

In [22]:
w = initial_w

In [23]:
compute_y_hat(X, w)

array([0., 0., 0., ..., 0., 0., 0.])

In [24]:
compute_logistic_loss(y, X, w)

3465.7359027997336

In [27]:
compute_logistic_gradient(y, X, w)

NameError: name 'X' is not defined

In [52]:
w

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
n_iter = 1

In [59]:
logistic_gradient = compute_logistic_gradient(y, X, w)

/Users/jonathandoenz/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: RuntimeWarning: invalid value encountered in true_divide
  


In [68]:
(tX == -999).sum()

31470

In [67]:
(X == 0).sum()

0

In [64]:
compute_logistic_stoch_gradient(y, X, w)

/Users/jonathandoenz/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: RuntimeWarning: invalid value encountered in true_divide
  


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan])

In [28]:
batch_size = 1
logistic_stochastic_gradient_descent(y, X, initial_w, batch_size, max_iters, gamma)


NameError: name 'X' is not defined

In [61]:
logistic_regression(y, X, initial_w, max_iters, gamma)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 5000)

In [60]:
logistic_gradient

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan])

In [55]:
loss = compute_logistic_loss(y, X, w)

In [56]:
w = w - gamma * logistic_gradient

In [57]:
w

array([-2107.        ,   354.35866821,  -837.8602899 ,   -63.6926945 ,
         510.55042855,   593.21413671,   551.00704147,  -458.88731536,
         -35.36022692,   -11.06128731,   413.29506493,  -430.42950507,
         712.44418214,   582.44782803,   584.73584261,    48.31126568,
         -34.01696442,   -46.7716998 ,    80.02060049,    48.2179738 ,
          87.81844147,    34.26825461,   356.47716284,   395.44979591,
         451.65065504,   -69.88303493,   -61.67485062,   312.36620516,
          14.728003  ,   -85.20603379,   369.61834816])

In [51]:
logistic_gradient_descent(y, X, initial_w, max_iters, gamma)

/Users/jonathandoenz/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: RuntimeWarning: invalid value encountered in true_divide
  


(nan, array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan]))

In [42]:
loss, w = logistic_regression(y, X, initial_w, max_iters, gamma, method)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 5000)

In [40]:
def compute_y_hat(tx, w):
    """Compute points tx estimated by model w: tx @ w."""
    return tx @ w

def compute_logistic_loss(y, tx, w):
    """Compute logistic loss function."""
    N = len(y)
    y_hat = compute_y_hat(tx, w)
    loss = ( np.log(1 + np.exp(y_hat)) - (y * y_hat) ) @ np.ones(N)
    return loss

def logistic_function(x):
    """Compute logistic function: f(x) = e^x / (1 + e^x)."""
    return np.exp(x) / (1 + np.exp(x))

def compute_logistic_gradient(y, tx, w):
    """Compute the gradient using logistic loss function."""
    N = len(y)
    y_hat = compute_y_hat(tx, w)
    return X.T @ (logistic_function(y_hat) - y)

def compute_logistic_stoch_gradient(y, tx, w):
    """Compute stochastic gradient using logistic loss function."""
    return compute_logistic_gradient(y, tx, w)

def logistic_gradient_descent(y, tx, initial_w, max_iters, gamma):
    """Logistic gradient descent algorithm.
    
    Parameters
    ----------
    y: n-by-1 array
        target vector
    tx: n-by-d array
        data vector
    initial_w: d-by-1 array
        initial model vector
    max_iters: int
        number of iterations to perform
    gamma: float
        step size
    
    Returns 
    -------
    loss: float
        Logistic error between target vector y and predicted points tx @ w
    w: d-by-1 array
        updated model
    """
    # model's weights' vector
    w = initial_w
    for n_iter in range(max_iters):
        # number of data points
        N = len(y)
        # compute logistic gradient
        logistic_gradient = compute_logistic_gradient(y, tx, w)
        # compute loss
        loss = compute_logistic_loss(y, tx, w)
        # update weights' vector
        w = w - gamma * logistic_gradient

    return loss, w

def logistic_stochastic_gradient_descent(y, tx, initial_w, batch_size, max_iters, gamma):
    """Logistic stochastic gradient descent algorithm.
    
    parameters
    ----------
    y: n-by-1 array
        target vector
    tx: n-by-d array
        data vector
    batch_size: int
        number of batches to sample
    initial_w: d-by-1 array
        initial model vector
    max_iters: int
        number of iterations to perform
    gamma: float
        step size
    
    returns 
    -------
    loss: float
        Logistic error between target vector y and predicted points tx @ w
    w: d-by-1 array
        updated model
    """
    # model's weights' vector
    w = initial_w
    for n_iter in range(max_iters):
        for minibatch_y, minibatch_tx in batch_iter(y, tx, batch_size):
            # compute logistic stochastic gradient
            logistic_stoch_gradient = compute_logistic_stoch_gradient(minibatch_y, minibatch_tx, w)
            # compute loss
            loss = compute_logistic_loss(y, tx, w)
            # update weights' vector
            w = w - gamma * stoch_gradient
            # print result to follow evolution of optimization
            # print("Logistic SGD ({bi}/{ti}): loss={l:.4f}".format(bi=n_iter,
            #                                                   ti=max_iters-1,
            #                                              l=loss))

    return loss, w


In [41]:
def logistic_regression(y, tx, initial_w, max_iters, gamma,
                        method="SGD"):
    """Logistic regression using SGD or GD.
    
    Parameters
    ----------
    y: n-by-1 array
        target vector
    tx: n-by-d array
        data vector
    initial_w: d-by-1 array
        initial model vector
    max_iters: int
        number of iterations to perform
    gamma: float
        step size
    method: string
        algorithm used
    
    Returns 
    -------
    loss: float
        Logistic error between target vector y and predicted points tx @ w
    w: d-by-1 array
        updated model
    """
    # print summary of regression
    # print_regression_summary(y, tx, initial_w, max_iters, gamma, method)
    
    # run regression
    if method == "GD":
        return logistic_gradient_descent(y, tx, initial_w, max_iters, gamma)
    else:
        batch_size = 1
        return logistic_stochastic_gradient_descent(y, tx, initial_w, batch_size, max_iters, gamma)

## Do your thing crazy machine learning thing here :) ...

## Generate predictions and save ouput in csv format for submission:

In [69]:
DATA_TRAIN_PATH = '/Users/jonathandoenz/Dropbox/EPFL_2018-2019/Semester_1/ML/ML_course/projects/project1/data/train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [70]:
DATA_TEST_PATH = '/Users/jonathandoenz/Dropbox/EPFL_2018-2019/Semester_1/ML/ML_course/projects/project1/data/test.csv' # TODO: download train data and supply path here 
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [31]:
OUTPUT_PATH = '' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)